Add files via upload
Exception error at line 59 to debug: 
java.lang.NullPointerException: Cannot invoke "String.length()" because "result" is null at ticTacToe.TicTacToe.main(TicTacToe.java:59)